/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package burp.redirector;

import javax.swing.SpinnerListModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author vagrant
 */
public class EditDialog extends javax.swing.JDialog {

    private RedirectRule rule;

    /**
     * Creates new form AddDialog
     */
    public EditDialog(java.awt.Frame parent, boolean modal, RedirectRule rule) {
        super(parent, modal);
        this.rule = rule;
        initComponents();
        cmbSourceProtocol.setSelectedIndex(rule.sProtocol);
        cmbRedirectProtocol.setSelectedIndex(rule.dProtocol);
        edtSourceHost.setText(rule.sHostname);
        editRedirectHost.setText(rule.dHostname);       
        ((SpinnerNumberModel)spnSourcePort.getModel()).setValue(rule.sPort);
        ((SpinnerNumberModel)spnRedirectPort.getModel()).setValue(rule.dPort);
        
        tblPaths.getModel().setValueAt(rule.sPath, 0, 0);
        tblPaths.getModel().setValueAt(rule.dPath, 0, 1);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        btnOK = new javax.swing.JButton();
        edtSourceHost = new javax.swing.JTextField();
        spnRedirectPort = new javax.swing.JSpinner();
        spnSourcePort = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        cmbRedirectProtocol = new javax.swing.JComboBox<>();
        cmbSourceProtocol = new javax.swing.JComboBox<>();
        editRedirectHost = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaths = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Specify the details of the redirection rule.");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        edtSourceHost.setBackground(new java.awt.Color(255, 255, 255));
        edtSourceHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtSourceHostActionPerformed(evt);
            }
        });

        spnRedirectPort.setModel(new javax.swing.SpinnerNumberModel(80, 1, 65535, 1));
        spnRedirectPort.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnRedirectPortStateChanged(evt);
            }
        });

        spnSourcePort.setModel(new javax.swing.SpinnerNumberModel(80, 1, 65535, 1));
        spnSourcePort.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnSourcePortStateChanged(evt);
            }
        });

        jLabel2.setText("----->");

        cmbRedirectProtocol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "HTTP", "HTTPS" }));

        cmbSourceProtocol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Any", "HTTP", "HTTPS" }));

        editRedirectHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editRedirectHostActionPerformed(evt);
            }
        });

        tblPaths.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"/(.*)", "/{0}"}
            },
            new String [] {
                "Original Path", "Mapped Path"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPaths);
        if (tblPaths.getColumnModel().getColumnCount() > 0) {
            tblPaths.getColumnModel().getColumn(0).setResizable(false);
            tblPaths.getColumnModel().getColumn(1).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbSourceProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edtSourceHost, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnSourcePort, javax.swing.GroupLayout.PREFERRED_SIZE, 86, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbRedirectProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editRedirectHost, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnRedirectPort, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnRedirectPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edtSourceHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnSourcePort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRedirectProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSourceProtocol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editRedirectHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.rule.sHostname = this.edtSourceHost.getText();
        this.rule.sProtocol = this.cmbSourceProtocol.getSelectedIndex();
        this.rule.sPort = (Integer) this.spnSourcePort.getValue();
        this.rule.dHostname = this.editRedirectHost.getText();
        this.rule.dProtocol = this.cmbRedirectProtocol.getSelectedIndex();
        this.rule.dPort = (Integer) this.spnRedirectPort.getValue();
        this.rule.sPath = (String) tblPaths.getModel().getValueAt(0, 0);
        this.rule.dPath = (String) tblPaths.getModel().getValueAt(0, 1);
        Redirector.getInstance().insertOrUpdate(this.rule);
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    private void edtSourceHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtSourceHostActionPerformed

    }//GEN-LAST:event_edtSourceHostActionPerformed

    private void spnRedirectPortStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnRedirectPortStateChanged

    }//GEN-LAST:event_spnRedirectPortStateChanged

    private void spnSourcePortStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnSourcePortStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spnSourcePortStateChanged

    private void editRedirectHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editRedirectHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editRedirectHostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cmbRedirectProtocol;
    private javax.swing.JComboBox<String> cmbSourceProtocol;
    private javax.swing.JTextField editRedirectHost;
    private javax.swing.JTextField edtSourceHost;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner spnRedirectPort;
    private javax.swing.JSpinner spnSourcePort;
    private javax.swing.JTable tblPaths;
    // End of variables declaration//GEN-END:variables
}
